# Generated by Django 3.1.4 on 2021-10-21 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='is_favorite',
            new_name='is_favourite',
        ),
    ]
